#spring:
#   application:
#    name: auth
#   jackson:
#    serialization-inclusion: non_empty
#   profiles:
#    active: dev

#---

server:
  port: 9999
  contextPath: /uaa

#---

#spring:
#  profiles: test
#  datasource:
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: jdbc:hsqldb:mem:auth
#    username: sa
#    password:
#    platform: hsqldb
#    data: classpath:database/data-hsqldb.sql
#    initialize: true
#    sql-script-encoding: UTF-8
#  jpa:
#    open-in-view: true
#    show-sql: true
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.HSQLDialect

#---

#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/auth?useSSL=false
#    username: root
#    password: pablo-1
#    platform: mysql
#    data: classpath:database/data-mysql.sql
#    initialize: true
#    sql-script-encoding: UTF-8
#  jpa:
#    open-in-view: true
#    show-sql: true
#    hibernate:
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      ddl-auto: create-drop
#      dialect: org.hibernate.dialect.MySQLDialect

#---

#facebook:
#  client:
#    clientId: 1984855458406529
#    clientSecret: d810b96a90eed9505693e6b5cdd16b53
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me

#---

#security:
#  sessions: if-required
#  user:
#    password: password
